"""Render sql/schema.sql and sql/indexes.sql from the ORM models.

The models are the source of truth. These two files exist so the schema can be
read in the browser without running anything, and they are regenerated rather
than edited:

    python scripts/dump_schema_sql.py

tests/test_schema_sync.py fails if they drift, so a forgotten regeneration shows
up in CI instead of in a code review.

    python scripts/dump_schema_sql.py --check   # exit 1 if out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from nupack_campaign.db import render_indexes_sql, render_schema_sql

SCHEMA_PATH = Path("sql/schema.sql")
INDEXES_PATH = Path("sql/indexes.sql")

SCHEMA_HEADER = """-- Generated by scripts/dump_schema_sql.py. Do not edit by hand.
-- The schema is defined in src/nupack_campaign/models.py.
--
-- Rendered for the SQLite dialect. Types map cleanly to Postgres apart from
-- INTEGER PRIMARY KEY, which would become SERIAL or IDENTITY there.

"""

INDEXES_HEADER = """-- Generated by scripts/dump_schema_sql.py. Do not edit by hand.
--
-- create_all() already builds these, the file is here so the indexes can be
-- read next to sql/select_candidates.sql and checked against it. Unique
-- constraints are not repeated here, they live in sql/schema.sql.

"""


def render() -> dict[Path, str]:
    return {
        SCHEMA_PATH: SCHEMA_HEADER + render_schema_sql(),
        INDEXES_PATH: INDEXES_HEADER + render_indexes_sql(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    stale: list[Path] = []
    for path, content in render().items():
        if args.check:
            current = path.read_text() if path.exists() else ""
            if current != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path}")

    if stale:
        names = ", ".join(str(path) for path in stale)
        print(f"out of date: {names}. Run python scripts/dump_schema_sql.py")
        return 1

    if args.check:
        print("schema files are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
