-- Generated by scripts/dump_schema_sql.py. Do not edit by hand.
-- The schema is defined in src/nupack_campaign/models.py.
--
-- Rendered for the SQLite dialect. Types map cleanly to Postgres apart from
-- INTEGER PRIMARY KEY, which would become SERIAL or IDENTITY there.

CREATE TABLE conditions (
    condition_id INTEGER NOT NULL,
    temperature_c FLOAT NOT NULL,
    na_molar FLOAT NOT NULL,
    mg_molar FLOAT NOT NULL,
    material VARCHAR(16) NOT NULL,
    ensemble VARCHAR(16) NOT NULL,
    PRIMARY KEY (condition_id),
    CONSTRAINT uq_conditions_point UNIQUE (temperature_c, na_molar, mg_molar, material, ensemble)
);

CREATE TABLE runs (
    run_id INTEGER NOT NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME,
    git_sha VARCHAR(40) NOT NULL,
    engine_name VARCHAR(32) NOT NULL,
    engine_version VARCHAR(32) NOT NULL,
    grid_hash VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    note TEXT,
    PRIMARY KEY (run_id),
    CONSTRAINT ck_runs_status CHECK (status IN ('running', 'complete', 'failed'))
);

CREATE TABLE targets (
    target_id INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL,
    sequence TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY (target_id),
    UNIQUE (name)
);

CREATE TABLE variants (
    variant_id INTEGER NOT NULL,
    name VARCHAR(96) NOT NULL,
    sequence TEXT NOT NULL,
    length_nt INTEGER NOT NULL,
    gc_content FLOAT NOT NULL,
    trunc_5prime INTEGER NOT NULL,
    trunc_3prime INTEGER NOT NULL,
    trunc_total INTEGER NOT NULL,
    position_1 INTEGER,
    original_base_1 VARCHAR(1),
    mutated_base_1 VARCHAR(1),
    mutation_type_1 VARCHAR(16) NOT NULL,
    position_2 INTEGER,
    original_base_2 VARCHAR(1),
    mutated_base_2 VARCHAR(1),
    mutation_type_2 VARCHAR(16) NOT NULL,
    num_transitions INTEGER NOT NULL,
    num_transversions INTEGER NOT NULL,
    num_mutations INTEGER NOT NULL,
    variant_class VARCHAR(24) NOT NULL,
    mutation_signature VARCHAR(64) NOT NULL,
    is_reference INTEGER NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (variant_id),
    CONSTRAINT ck_variants_length_positive CHECK (length_nt > 0),
    CONSTRAINT ck_variants_gc_range CHECK (gc_content BETWEEN 0 AND 1),
    CONSTRAINT ck_variants_mutation_count CHECK (num_mutations BETWEEN 0 AND 2),
    CONSTRAINT ck_variants_trunc CHECK (trunc_5prime >= 0 AND trunc_3prime >= 0),
    UNIQUE (name)
);

CREATE TABLE results (
    result_id INTEGER NOT NULL,
    run_id INTEGER NOT NULL,
    variant_id INTEGER NOT NULL,
    target_id INTEGER NOT NULL,
    condition_id INTEGER NOT NULL,
    cdna_dg_kcal FLOAT NOT NULL,
    complex_dg_kcal FLOAT NOT NULL,
    delta_g_binding_kcal FLOAT NOT NULL,
    mfe_kcal FLOAT,
    ensemble_defect FLOAT,
    compute_seconds FLOAT,
    PRIMARY KEY (result_id),
    CONSTRAINT uq_results_cell UNIQUE (run_id, variant_id, target_id, condition_id),
    FOREIGN KEY(run_id) REFERENCES runs (run_id) ON DELETE CASCADE,
    FOREIGN KEY(variant_id) REFERENCES variants (variant_id),
    FOREIGN KEY(target_id) REFERENCES targets (target_id),
    FOREIGN KEY(condition_id) REFERENCES conditions (condition_id)
);

CREATE TABLE selections (
    selection_id INTEGER NOT NULL,
    run_id INTEGER NOT NULL,
    created_at DATETIME NOT NULL,
    criteria_json TEXT NOT NULL,
    sql_sha256 VARCHAR(64) NOT NULL,
    n_candidates_in INTEGER NOT NULL,
    n_selected INTEGER NOT NULL,
    PRIMARY KEY (selection_id),
    FOREIGN KEY(run_id) REFERENCES runs (run_id)
);

CREATE TABLE target_energies (
    target_energy_id INTEGER NOT NULL,
    run_id INTEGER NOT NULL,
    target_id INTEGER NOT NULL,
    condition_id INTEGER NOT NULL,
    free_energy_kcal FLOAT NOT NULL,
    PRIMARY KEY (target_energy_id),
    CONSTRAINT uq_target_energy_cell UNIQUE (run_id, target_id, condition_id),
    FOREIGN KEY(run_id) REFERENCES runs (run_id) ON DELETE CASCADE,
    FOREIGN KEY(target_id) REFERENCES targets (target_id),
    FOREIGN KEY(condition_id) REFERENCES conditions (condition_id)
);

CREATE TABLE selection_members (
    selection_id INTEGER NOT NULL,
    variant_id INTEGER NOT NULL,
    rank INTEGER NOT NULL,
    delta_g_binding_kcal FLOAT NOT NULL,
    ddg_vs_reference_kcal FLOAT,
    PRIMARY KEY (selection_id, variant_id),
    CONSTRAINT uq_selection_rank UNIQUE (selection_id, rank),
    FOREIGN KEY(selection_id) REFERENCES selections (selection_id) ON DELETE CASCADE,
    FOREIGN KEY(variant_id) REFERENCES variants (variant_id)
);
