-- Generated by scripts/dump_schema_sql.py. Do not edit by hand.
--
-- create_all() already builds these, the file is here so the indexes can be
-- read next to sql/select_candidates.sql and checked against it. Unique
-- constraints are not repeated here, they live in sql/schema.sql.

-- conditions
CREATE INDEX idx_conditions_temperature ON conditions (temperature_c);

-- runs
CREATE INDEX idx_runs_status_started ON runs (status, started_at);

-- variants
CREATE INDEX idx_variants_class ON variants (variant_class);
CREATE INDEX idx_variants_gc ON variants (gc_content);
CREATE INDEX idx_variants_position_1 ON variants (position_1);
CREATE INDEX idx_variants_reference_lookup ON variants (num_mutations, trunc_5prime, trunc_3prime);
CREATE INDEX idx_variants_trunc ON variants (trunc_total, trunc_5prime, trunc_3prime);

-- results
CREATE INDEX idx_results_ranking ON results (run_id, condition_id, delta_g_binding_kcal);
CREATE INDEX idx_results_run_variant ON results (run_id, variant_id);

-- selections
CREATE INDEX idx_selections_run ON selections (run_id);

-- variant_alignments
CREATE INDEX idx_alignment_offset ON variant_alignments (target_id, target_offset);
CREATE INDEX idx_alignment_paired ON variant_alignments (target_id, n_complementary);
